### PR TITLE
Add stop node instructions

### PR DESCRIPTION
**Pull request by davidgumberg**

### CODE REVIEW

**Comment by tdb3** [comment]
The netinfo backcompat v25 bitcoin.conf should be:

```bash
echo "regtest=1" > $DATA_DIR_25/bitcoin.conf
echo "[regtest]" >> $DATA_DIR_25/bitcoin.conf
echo "rpcallowip=127.0.0.1" >> $DATA_DIR_25/bitcoin.conf
echo "rpcbind=127.0.0.1:18243" >> $DATA_DIR_25/bitcoin.conf
echo "rpcport=18243" >> $DATA_DIR_25/bitcoin.conf
echo "bind=127.0.0.1:18244" >> $DATA_DIR_25/bitcoin.conf
echo "bind=127.0.0.1:18245=onion" >> $DATA_DIR_25/bitcoin.conf
```

**Comment by tdb3** [comment]
> The netinfo backcompat v25 bitcoin.conf should be:
> 
> ```shell
> echo "regtest=1" > $DATA_DIR_25/bitcoin.conf
> echo "[regtest]" >> $DATA_DIR_25/bitcoin.conf
> echo "rpcallowip=127.0.0.1" >> $DATA_DIR_25/bitcoin.conf
> echo "rpcbind=127.0.0.1:18243" >> $DATA_DIR_25/bitcoin.conf
> echo "rpcport=18243" >> $DATA_DIR_25/bitcoin.conf
> echo "bind=127.0.0.1:18244" >> $DATA_DIR_25/bitcoin.conf
> echo "bind=127.0.0.1:18245=onion" >> $DATA_DIR_25/bitcoin.conf
> ```

Otherwise, we'll have a port conflict when running both nodes simultaneously.

**Comment by tdb3** [comment]
ACK f3bb88cf02c9fd6c99797d2a9b9018b633e711a3

**Comment by davidgumberg** [comment]
ACK https://github.com/tdb3/bitcoin_core_testing/commit/f3bb88cf02c9fd6c99797d2a9b9018b633e711a3

**Pull request merged**
